apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.parent.name }}-{{ .Chart.Name }}-memcache
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "memcache" . }}
    spec:
      containers:
      - name: memcache
        image: "{{ .Values.images.memcache }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: {{.Values.service.memcache.port }}
        resources:
{{ toYaml .Values.resources.memcache | indent 12 }}