apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.parent.name }}-{{ .Chart.Name }}
  labels:
    app: {{ include "name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - port: {{ .Values.ClientPort }}
    name: client
  selector:
    app: {{ include "name" . | quote }}
    release: {{ .Release.Name | quote }}
