apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.parent.name }}-{{ .Chart.Name }}-headless
  labels:
    app: {{ include "name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - port: {{ .Values.ServerPort }}
    name: server
  - port: {{ .Values.LeaderElectionPort }}
    name: leader-election
  clusterIP: None
  selector:
    app: {{ include "name" . | quote }}
    release: {{ .Release.Name | quote }}
