apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ template "fullname" . }}'
data:
  elevationd.conf: |-
    [elevationd]
    account_list_ttl = 900
    worker_loop_wait = 5
    worker_work_limit = 15
    statement_timeout = 30000
    staged_ap_limit = 10000

    [zadmin]
    conf = /opt/zonar/etc/zadmin.xml
    #conf = /home/josh/zadmin.xml

    [cassandra]
    keyspace = SRTM
    conf = /opt/zonar/etc/cassandra.xml
    pool_size = 100
    recycle = 50

    [loggers]
    # keys = root, elevationd
    keys = root, elevationd, srtmlib

    [handlers]
    keys = syslog, console

    [formatters]
    keys = generic

    [logger_root]
    level = INFO
    handlers = syslog

    [logger_elevationd]
    level = INFO
    handlers = syslog
    qualname = elevationd

    [logger_srtmlib]
    level = DEBUG
    handlers = syslog
    qualname = srtmlib

    [handler_console]
    class = StreamHandler
    args = (sys.stderr,)
    level = WARN
    formatter = generic

    [handler_syslog]
    class = handlers.SysLogHandler
    facility = LOG_LOCAL5
    args=('/dev/log', handlers.SysLogHandler.LOG_LOCAL5)
    level = INFO
    formatter = generic

    [formatter_generic]
    format=%(name)s - %(asctime)s - %(threadName)s - %(levelname)s - %(message)s
    datefmt=%Y-%m-%d %H:%M:%S
    class=logging.Formatter